server:
  port: 8082
spring:
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    password: fzvarxpndockbaeg
    username: 1510161612@qq.com
    port: 587
  rabbitmq:
    username: guest
    password: guest
    host: 124.223.27.13
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
  redis:
    host: 124.223.27.13
    port: 63379
    password: password
    database: 0